# Generated by Django 5.1.4 on 2024-12-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.AddField(
            model_name='testmodel',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
